import * as images from '../assets/images/images';
import { Movie, ParentGuideRatings } from '../types/models';

export const movies: Movie[] = [
  {
    favorite: true,
    id: 'anyone-but-you',
    seen: ['2024'],
    title: 'Anyone But You',
    actors: ['Glen Powell', 'Sydney Sweeney'],
    poster: images.anyoneButYouImage,
    rating: 'R' as ParentGuideRatings,
    releaseYear: 2023,
    runTime: 103,
    myRating: 8,
  },
  {
    favorite: false,
    id: 'aquaman-and-the-lost-kingdom',
    seen: ['2024'],
    title: 'Aquaman and the Lost Kingdom',
    actors: ['Jason Momoa', 'Patrick Wilson'],
    poster: images.aquaman_two,
    rating: 'PG-13',
    releaseYear: 2023,
    runTime: 124,
    myRating: 3,
  },
  {
    favorite: false,
    id: 'dune',
    seen: ['2024'],
    title: 'Dune',
    actors: ['Timothée Chalamet', 'Zendaya'],
    poster: images.duneImage,
    rating: 'PG-13',
    releaseYear: 2021,
    runTime: 155,
    myRating: 9,
  },
  {
    favorite: false,
    id: 'dune-part-two',
    seen: ['2024'],
    title: 'Dune 2',
    actors: ['Timothée Chalamet', 'Zendaya'],
    poster: images.duneTwoImage,
    rating: 'PG-13',
    releaseYear: 2024,
    runTime: 166,
    myRating: 9,
  },
  {
    favorite: false,
    id: 'the-librarian-quest-for-the-spear',
    seen: ['2024'],
    title: 'The Librarian: Quest for the Spear',
    actors: ['Noah Wyle', 'Sonya Walger'],
    poster: images.librarianOneImage,
    rating: 'NR',
    releaseYear: 2004,
    runTime: 92,
    myRating: 7,
  },
  {
    favorite: false,
    id: 'the-librarian-return-to-king-solomons-mine',
    seen: ['2024'],
    title: "The Librarian: Return to King Solomon's Mine",
    actors: ['Noah Wyle', 'Gabrielle Anwar'],
    poster: images.librarianTwoImage,
    rating: 'TV-PG',
    releaseYear: 2006,
    runTime: 92,
    myRating: 6,
  },
  {
    favorite: false,
    id: 'the-librarian-the-curse-of-the-judase-chalice',
    seen: ['2024'],
    title: 'The Librarian: The Curse of the Judas Chalice',
    actors: ['Noah Wyle', 'Stana Katic'],
    poster: images.librarianThreeImage,
    rating: 'TV-PG',
    releaseYear: 2008,
    runTime: 90,
    myRating: 6,
  },
  {
    favorite: false,
    id: 'ricky-stanicky',
    seen: ['2024'],
    title: 'Ricky Stanicky',
    actors: ['Zac Efron', 'John Cena'],
    poster: images.rickyStanickyImage,
    rating: 'R',
    releaseYear: 2024,
    runTime: 113,
    myRating: 5,
  },
  {
    favorite: false,
    id: 'roadhouse',
    seen: ['2024'],
    title: 'Roadhouse',
    actors: ['Jake Gyllenhaal', 'Daniela Melchior'],
    poster: images.roadhouseNewImage,
    rating: 'R',
    releaseYear: 2024,
    runTime: 121,
    myRating: 5,
  },
  {
    favorite: false,
    id: 'wonka',
    seen: ['2024'],
    title: 'Wonka',
    actors: ['Timothée Chalamet', 'Gustave Die'],
    poster: images.wonkaImage,
    rating: 'PG',
    releaseYear: 2023,
    runTime: 116,
    myRating: 8,
  },
];
